### ISSUE TITLE
Inform the user the IBAN is wrong instead of 'Something went wrong'

### ISSUE THREAD

**Issue by TobiasDeBruijn** [svsticky/digidecs#15]

**Comment by MarcelvLaar** [comment]
I assume this is solved by an 11-test in the frontend, so https://github.com/svsticky/digidecs/pull/16

**Comment by TobiasDeBruijn** [comment]
The backend does the validation already, basically just need to pass the error back to the dialog, rather than just using the default message.

**Comment by TobiasDeBruijn** [comment]
I think this can be closed due to #16 . The frontend handles the check (as well as the backend, but that doens't matter anymore)
