### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by martijncasteel** [svsticky/digidecs#4]
This is a perfect example of an app that can benefit from the Oauth api from Stickyutrecht/ConstipatedKoala@0884b8cd87ed07302ea73cbada0e0496475cd22e it allows this app to store information about the user such as bank account (if they want to) and fill in the form using `/api/members/:id`. 

Also if we have a very eager treasurer he or she should be able to login to retrieve the information otherwise send by email and mark the declaration as paid, pending, or denied with a reason. Maybe this should be made possible with a url in the email to set it at paid (awesome, no login required if cookie is still present ^^)

**Comment by martijncasteel** [comment]
@tomwassenberg @duijf I hate myself :smile:

**Comment by duijf** [comment]
I think this is outside of the scope for now and needs to be defined further in the future if we want to pursue this.
