### ISSUE TITLE
Increase upload limit

### ISSUE THREAD

**Issue by duijf** [svsticky/digidecs#5]
Most phone cameras take pics that are larger than 2MB. We can do some compression on the server,
or just send bigger attachments.

**Comment by tomwassenberg** [comment]
The size is 100MB in the current code, which is probably a typo, since the labels mention 10MB. Mailgun's limit is 25MB, so I changed it in production to 20MB. I suggest changing this in config.example.php, `templates/form.php` and `index.php` too.

**Comment by tomwassenberg** [comment]
> The size is 100MB in the current code, which is probably a typo, since the labels mention 10MB. Mailgun's limit is 25MB, so I changed it in production to 20MB. I suggest changing this in config.example.php, `templates/form.php` and `index.php` too.

Was fixed in the mean time.
